using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Markup;
using Microsoft.Win32;
using Path = System.IO.Path;

namespace WKProjectSolver;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class ProjectResolver : Window
{
    public ProjectResolver()
    {
        InitializeComponent();
    }
    
    private void Browse_Click(object sender, RoutedEventArgs e)
    {
        var folderDialog = new OpenFolderDialog
        {
            Title = "Select Folder",
            InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),
        };

        if (folderDialog.ShowDialog() != true) return;
        var folderName = folderDialog.FolderName;
        FolderPathBox.Text = folderName;
    }

    private void Resolve_Click(object sender, RoutedEventArgs e)
    {
        var unityFolder = FolderPathBox.Text;

        if (string.IsNullOrEmpty(unityFolder))
        {
            MessageBox.Show("Please select a folder first.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            return;
        }

        if (!Directory.Exists(unityFolder) || !Directory.Exists(Path.Combine(unityFolder, "Assets")))
        {
            MessageBox.Show("Please select a valid Unity project folder.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            return;
        }

        // Delete files generated by Unity
        Delete_File(Path.Combine(unityFolder,
            @"Assets\Plugins\Assembly-CSharp-firstpass\UnitySourceGeneratedAssemblyMonoScriptTypes_v1.cs"));
        Delete_File(Path.Combine(unityFolder,
            @"Assets\Scripts\Assembly-CSharp\UnitySourceGeneratedAssemblyMonoScriptTypes_v1.cs"));

        // Replace shaders
        ReplaceShaders(unityFolder);

        // Delete burst and mathematics files
        DeleteBurstAndMathematicsFiles(unityFolder);
        
        // Add input files
        CopyInputFiles(unityFolder);

        if (Copy_File(Path.Combine(Directory.GetCurrentDirectory(), "Scripts", "ProjectFixer.cs"),
                Path.Combine(unityFolder, "Assets", "Editor")))
        {
            AddedScript.IsChecked = true;
        }

        MessageBox.Show("Project resolve successful.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
    }

    private void ReplaceShaders(string projectPath)
    {
        var shaders = Directory.GetFiles(Path.Combine(Directory.GetCurrentDirectory(), "Shaders"), "*.shader");
        var cgincs = Directory.GetFiles(Path.Combine(Directory.GetCurrentDirectory(), "Shaders"), "*.cginc*");
        
        var shadersResults = shaders.Select(file => Copy_File(file, Path.Combine(projectPath, "Assets", "Shader"))).ToList();
        var cgincsResults = cgincs.Select(file => Copy_File(file, Path.Combine(projectPath, "Assets", "Shader"))).ToList();

        if (shadersResults.Contains(false) || cgincsResults.Contains(false))
        {
            MessageBox.Show("Failed to copy shader files.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        else
        {
            ReplacedShaders.IsChecked = true;
        }
    }

    private void DeleteBurstAndMathematicsFiles(string projectPath)
    {
        var burstFiles = Directory.GetFiles(projectPath, "*burst*", SearchOption.AllDirectories);
        var mathFiles = Directory.GetFiles(projectPath, "*mathematics*", SearchOption.AllDirectories);
        
        var burstResults = burstFiles.Select(Delete_File).ToList();
        var mathResults = mathFiles.Select(Delete_File).ToList();
        
        if (burstResults.Contains(false) || mathResults.Contains(false))
        {
            MessageBox.Show("Failed to delete burst and mathematics files.");
            return;
        }

        RemovedBurstMathematics.IsChecked = true;
    }

    private void CopyInputFiles(string projectPath)
    {
        var destDir = Path.Combine(projectPath, "Assets", "Input");
        var inputFiles = Directory.GetFiles(Directory.GetCurrentDirectory(), "Extras");
        Directory.CreateDirectory(destDir);
        foreach (var inputFile in inputFiles)
        {
            Copy_File(inputFile, destDir);
        }

        CopiedInputFiles.IsChecked = true;
    }
    
    private void Log(string message)
    {
        LogConsole.AppendText($"[{DateTime.Now:HH:mm:ss}] {message}\n");
        LogConsole.ScrollToEnd();
    }
    
    private bool Copy_File(string sourceFile, string destDir)
    {
        if (!File.Exists(sourceFile))
        {
            Log($"File {sourceFile} does not exist.");
            return false;
        }
        
        if (!Directory.Exists(destDir))
        {
            Log($"Folder {destDir} does not exist.");
            return false;
        }

        var fileName = Path.GetFileName(sourceFile);
        
        File.Copy(sourceFile, Path.Combine(destDir, fileName), true);
        Log($"Copied {sourceFile} to {fileName}");
        return true;
    }

    private bool Delete_File(string path)
    {
        if (!File.Exists(path))
        {
            Log($"File {path} does not exist.");
            return false;
        }

        File.Delete(path);
        Log($"Deleted {path}");
        return true;
    }
}