name: Deploy WK Project Resolver

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: WKPRojectSolver/WKProjectSolver.csproj

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build app
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

    - name: Publish app
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: publish/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
